version: '3'
services: 
  app:
    env_file: .env
    environment:
      - REDIS_HOST=redis
    ports: 
      - "8080:8080"
    build: .
    restart: on-failure
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
